eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@registry-app:8761/eureka

spring:
  cloud:
    config:
      uri: http://registry-app:8761/config
      username: admin
      password: admin
  boot:
    admin:
      client:
        url: http://registry-app:8761/admin
        username: admin
        password: admin

sapient:
  jwt:
    secret: NjBlZTZmNjVhYTRlMTdiNzM3NGIwNDFhOTRlYmUxNWYxMzEyNDFkZTU5ZjI0ZmQ4MGE3ZDU2ZTY5NjE5YTk1ZmQzNDc2OGQ1Yjc5ZTI4MzMzMTk4N2ExMTVjN2NiMTZlMmNkOQ
    validityInSeconds: 600
    
logging:
  level:
    ROOT: info
    com.sapient.authserver: debug
    com.sapient.registry: debug
